### ISSUE TITLE
Using models other than the ones provided gives errors

### ISSUE THREAD

**Issue by RV05** [ValYouW/tflite-win-c#1]
Hi,
I would like to know the following things:
can you mention the training methodology for all the models that you have provided in this repo(object detection, segmentation and style transfer). Or if these are pretrained models, can you give me the link to the documentation that mentions their training methodology 

The models that i  have trained are not working with the code provided. Hence would like to know the training strategy so that i can train the models on my own dataset.

Thanks

**Comment by ValYouW** [comment]
Hi,

These are pre-trained models:
1) Object Detection is taken from Google's MediaPipe project, you can use their model to do "transfer learning" and it should work (I did that at my workplace).
2) Segmentation is Google's DeppLab model
3) Style Transfer was contributed by someone, I am not sure how it was trained.

Closing this issue but feel free to ask questions if you have.
