### ISSUE TITLE
Usage of C library in windows : tensorflow C api [cpu only]

### ISSUE THREAD

**Issue by rohit-kumar-j** [ValYouW/tflite-win-c#2]
I am coming from your [youtube video](https://www.youtube.com/watch?v=dox1ZkFP-f4&feature=youtu.be&ab_channel=TheCodingNotebook), but for tensorflow API, not tensorflow lite, Here is my question:

I want to use [this C library](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.9.1.zip) from [here](https://www.tensorflow.org/install/lang_c) on windows globally. I intend to run the `hello_tf.c` example natively on windows with the global install (like how `#include <stdio.h>` -> `#include <tensorflow/c/c_api.h>` is available. Is this possible?)
I've looked at StackOverflow multiple times and was not able to figure it out. I was getting this error:
```bash
$> gcc hello_tf.c -ltensorflow -o hello_tf     
hello_tf.c: In function 'main':
hello_tf.c:7:60: warning: implicit declaration of function 'TF_Version' [-Wimplicit-function-declaration]
    7 |     printf("Hello from TensorFlow C library version %s\n", TF_Version());
      |                                                            ^~~~~~~~~~
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ltensorflow
collect2.exe: error: ld returned 1 exit status
```  

I know this is a trivial error, but I cannot figure out how to proceed from here. Below is the source code:

```C
// hello_tf.c
#include <stdio.h>
#include <tensorflow/c/c_api.h>

int main() {
  printf("Hello from TensorFlow C library version %s\n", TF_Version());
  return 0;
}
```

**Comment by ValYouW** [comment]
Hi,
I'm not an expert on using gcc on windows, the error is pretty much saying the linker can't find the library.
See here: https://www.tensorflow.org/install/lang_c#linker
You should configure LIBRARY_PATH and LD_LIBRARY_PATH to include the folder where the tensor flow lib is. Maybe also try to put it on your PATH just to be safe.
Other than that I really don't know....
